### ISSUE TITLE
Gebruiken data uit persoonscase voor conditions in uitgiftecase.

### ISSUE THREAD

**Issue by barthoeksma** [EdwinSmink/Gemboxx#19]
Na lang ploeteren toch maar een issue aangemaakt want het wil niet lukken:
we hebben in de persoonsgegevenscase een attribuut "Recht op rijbewijs" dat we in de uitgiftecase
willen gebruiken om te bepalen of een aanvraag valide is.
We hebben via attributes op platformniveau geprobeerd, via queries op de forms en uit wanhoop zelfs door een functie voor een value in te voeren, maar het levert allemaal niet het gewenste resultaat.
Het leerboek laat alleen zien hoe het met een ID moet (die je direct uit de metadata kunt halen).
De stap van daar naar de afzonderlijke attributen snap ik alleen niet.

**Comment by EdwinSmink** [comment]
Kun je de case meegeven? Dan kan ik het laten zien.
Als eerste stap heb je de case id (in het voorbeeld hieronder staat die in houdercase) de  van de persoonscase nodig. Daarna kun je op de map in van de activiteit het volgende doen:

![rijbewijs mappen](https://cloud.githubusercontent.com/assets/4785950/6570420/65fd1c6a-c6fa-11e4-8058-63c38a268b3d.PNG)

**Comment by barthoeksma** [comment]
Als je met "de case meegeven" een link naar de trainingsbox bedoelt waar we in werken:
https://dev.grexx.net/TrainingGemboxx29_O/person/case.jsp?case=1831448@TrainingGemboxx29.nl&stm=1425973084070
Ik ga die oplossing proberen in de tussentijd.

**Comment by EdwinSmink** [comment]
Ik wil graag de URL naar de case. Dus als je in Uitgifte rijbewijs bezig bent staat er een URL die verwijst naar de rijbewijs case waar je in bezig bent. De URL die nu gegeven is verwijst naar iets anders. Ik heb ondertussen wel een case gevonden:
https://dev.grexx.net/TrainingGemboxx29_O/person/case.jsp?case=1831859&stm=1425973295390

**Comment by barthoeksma** [comment]
Dat is inderdaad onze uitgiftecase, mocht je onze persoonsgegevenscase ook nodig hebben voor de uitleg, die staat hier: https://dev.grexx.net/TrainingGemboxx29_O/person/case.jsp?case=1831853@TrainingGemboxx29.nl&stm=1425973575396

**Comment by EdwinSmink** [comment]
Vanuit de uitgifte moet je eerst een persoon kunnen selecteren, dat zie ik nog niet. Als je dat hebt dan heb je ook de case id te pakken. Als je dan gaat valideren geef je in de map in van de activiteit mee een map in als eerder aangegeven

**Comment by barthoeksma** [comment]
Het selecteren van een persoon gebeurt op de startform van de uitgiftecase, maar grexx pakt dus automatisch de ID van het persoonsdossier dat je hebt gekozen?

**Comment by EdwinSmink** [comment]
Je moet dan wel het attribuut als type 'case' definieren.

**Comment by barthoeksma** [comment]
Ok, ik heb het attribuut ID_Persoonsdossier in de persoonscase (type case), en ik heb hem op allebei de cases op de form gezet voor het testen, maar als ik de MAP IN probeer te maken kan ik alleen uit CaseMetaData-attributen selecteren, de ServiceInput is nergens te bekennen.

**Comment by EdwinSmink** [comment]
Ik heb case attribuut persoonsdossier ook asl case gemaakt. Het gaat er uiteindelijk om dat we bij het validatie scherm dan de attributen tonen (en dus opnemen op het form) naam persoon en recht op rijbewijs. De map in is dan op de validatie scherm. Je moet de taken nmog wel klaar zetten
