### ISSUE TITLE
Personencase

### ISSUE THREAD

**Issue by Olivierkranenburg** [EdwinSmink/Gemboxx#20]
Wij zijn bezig met COB-23 maar weten niet hoe we een persoon uit de personencase moeten halen.
In de opdracht staat dat we gebruik  moeten maken van de modellering van contactpersonen voor de attributen bij een persoon. Hier staat echter geen BSN, vreemdelingennummer oid bij dus hoe kunnen we iemand identificeren en uit de personencase selecteren?

**Comment by EdwinSmink** [comment]
Probeer te zoeken op naam. Maak een grid met de personen waarvoor nog geen IND is langs geweest en selecteer dan op naam. Dit kan door naam attribuut op de widget in de conditie gelijk te stellen aan de ingevoerde naam of je kunt op de widget een zoek/functie definieren door velden op te nemen in de zoek.

**Comment by EdwinSmink** [comment]
Dus een widget met alle personen. Bij het toevoegen van een attribuut kun je een vinkje zetten bij InQueryForm. Dit attribuut wordt dan gebruikt als filter optie
