### ISSUE TITLE
Geen opties meer?

### ISSUE THREAD

**Issue by CoenPijpers** [EdwinSmink/Gemboxx#21]
![image](https://cloud.githubusercontent.com/assets/11281019/6668452/5ce40e7e-cbf3-11e4-82b2-60dad2759471.png)

Sinds 2 minuten hebben wij ineens geen opties meer om uit te voeren.
We hebben niks veranderd aan rollen e.d.

**Comment by EdwinSmink** [comment]
Klopt dat jullie niets veranderd hebben aan de rollen. Het zetten van de state op het platform wordt ten zeerste afgeraden want dan verdwijnen alle opties aangezien de state> 1000 ook de case afsluit en dat is niet wat je op het platform wilt.

**Comment by CoenPijpers** [comment]
Platform was inderdaad door een state in een eindstate gekomen, waardoor de case platform dus niks meer mee gedaan kon worden. Nu opgelost!
