### ISSUE TITLE
Selecte data uit case in een widget in andere case

### ISSUE THREAD

**Issue by RAVerboon** [EdwinSmink/Gemboxx#22]
We hebben een case "Evenement" en een case "Contactpersonen". Voor een evenement willen we contactpersonen uitnodigen.
Contactpersonen is opgebouwd zoals Producten in de veggieburger, er is dus een startform waarna deze gegevens in een widget komen. 
Wij hebben bij Evenement een activiteit toegevoegd genaamd "Mensen uitnodigen" met daarin de een verrekijkertje waarin je mensen uit de case Contactpersonen kan selecteren. Daarnaast hebben we in Evenement ook een gridwidget waar we de Uitgenodigden in willen zien, maar nadat er mensen zijn geselecteerd en er op opslaan is gedrukt word er niks in deze widget laten zien.

**Comment by EdwinSmink** [comment]
Kun je de link naar de boxx waarin het staat aanleveren? 
Ik vermoed dat je er geen relation widget van hebt gemaakt die gekoppeld is aan het attribuut waarin je de genodigde vastlegt die je geselecteerd hebt.

**Comment by RAVerboon** [comment]
Dit is een link naar en van de eveement cases.
https://dev.grexx.net/TrainingGemboxx32_O/person/case.jsp?case=1833104@TrainingGemboxx32.nl&stm=1426593412141

**Comment by EdwinSmink** [comment]
Ik heb een aparte widget gercreerd van het type 'Relation widget'. Deze heb ik laten verwijzen naar de widget op het platform (2884).  De widget op het platform heb ik ook als relation source aangevinkt (zie advanced in de definitie van de widget).
Ik heb het attribuut contactpersoon multivalue gemaakt in de case data en nu heb je een widget waarin de geselecteerde genodigde zitten. Er staan twee leege regels in maar dat lijkt te wijten aan beperkte informatie in de contatcpersonen

**Comment by RAVerboon** [comment]
Heel erg bedankt, we zouden er zelf nooit achtergekomen zijn dat het zo zou moeten.
