### ISSUE TITLE
Relatie HECS - IND - vreemdeling

### ISSUE THREAD

**Issue by Olivierkranenburg** [EdwinSmink/Gemboxx#23]
Wij vragen ons af wat precies de afspraken inhouden die worden gemaakt door de IND het HECS en de vreemdeling. COB-23, 16, 24, 20, 18,  en 22 zijn gedaan, maar bij 21 wil de medewerker van de IND een overzicht van de afspraken, welke afspraken? Er zijn alleen afspraken gemaakt etc door het HECS.

**Comment by EdwinSmink** [comment]
Het gaat hier om agenda afspraken waarbij de IND de verblijfspas kan overhandigen. Dus er wordt met de expat afgesproeken wanneer deze ten kantore moet verschijnen om de verblijfspas en de inschrijving in de BRP/GBA te regelen.

**Comment by Olivierkranenburg** [comment]
oke, en dan hebben we nog een vraagje. We willen in een widget alleen afspraken laten tonen van de eerstvolgende week (COB-21) maar dan moeten we de waarde van de volgende week krijgen wat dan steeds wordt aangepast in de widget, we weten alleen niet hoe. Enig idee?

**Comment by EdwinSmink** [comment]
Je kunt een date bereken door bijv now() + 7 dagen te doen in een map out. Dan stop je die waarde in variabele waarmee je de widget filtert. Het is dan wel nodig om een taak te hebben : toon afspraken volgende week waarbij je aangeeft wat de eerste

**Comment by EdwinSmink** [comment]
Wil je bij vragen de URL van de case/box meegeven dan kan ik even meekijken

**Comment by Olivierkranenburg** [comment]
We komen er nog niet echt uit, dit is de link naar platform home (waar de widget staat):
https://dev.grexx.net/TrainingGemboxx40_O/person/case.jsp?case=1825291@TrainingGemboxx40.nl&stm=1426622263711

**Comment by Olivierkranenburg** [comment]
Het is al gelukt, nu alleen nog ervoor zorgen dat de er geen datum uit het verleden kan worden gekozen. Er was wel ineens een conditie verdwenen, weet niet of je er nu in zit te werken

**Comment by EdwinSmink** [comment]
Ik zit er inderdaad in dus misschien weer stuk of juist weer wel. Ik blijf er nu 5 minuten af

**Comment by EdwinSmink** [comment]
Grappig, die conditie stond er straks toch ook in?

**Comment by Olivierkranenburg** [comment]
Hahah, er veranderde op magische wijze van alles dat verklaart het. Maar het is gelukt dank:) enig idee hoe we er nu nog voor kunnen zorgen dat bij het maken van afspraak er geen datum uit het verleden kan worden gekozen? Ja die conditie stond er al in..

**Comment by EdwinSmink** [comment]
Ja, met JavaScript. Moet ik opzoek gaan waar ik dat eerder heb gebruikt. Net geprobeerd lijkt niet te werken. Wel eerste deel maar dan heb je maar 1 datum dus kijk maar of jullie er chocolade van kunnen maken. Let op, open de case ook in een andere browser want JS kan een en ander kapot maken en al helemaal op het platform is het fataal/vervelend.

//Calculating Startdate
var today = new Date();
var dd = today.getDate()-1;
var mm = today.getMonth()+1; //January is 0!
var yyyy = today.getFullYear();

if(dd<10){
  dd='0'+dd
} 
if(mm<10){
   mm='0'+mm
} 
var startdate = yyyy+'-'+mm+'-'+dd;
//

//Adding months
Date.isLeapYear = function (year) { 
    return (((year % 4 === 0) && (year % 100 !== 0)) || (year % 400 === 0)); 
};

Date.getDaysInMonth = function (year, month) {
    return [31, (Date.isLeapYear(year) ? 29 : 28), 31, 30, 31, 30, 31, 31, 30, 31, 30, 31][month];
};

Date.prototype.isLeapYear = function () { 
    return Date.isLeapYear(this.getFullYear()); 
};

Date.prototype.getDaysInMonth = function () { 
    return Date.getDaysInMonth(this.getFullYear(), this.getMonth());
};

Date.prototype.addMonths = function (value) {
    var n = this.getDate();
    this.setDate(1);
    this.setMonth(this.getMonth() + value);
    this.setDate(Math.min(n, this.getDaysInMonth()));
    return this;
};
//


//Calculating Enddate
var addmonth = today.addMonths(3);
var endyear = addmonth.getFullYear();
var endmonth = addmonth.getMonth()+1;
var endday = addmonth.getDate();

if (endmonth < 10)
  {
      endmonth = '0'+endmonth;
  }
if (endday < 10)
  {
      endday = '0'+endday;
  }
var enddate = endyear+'-'+endmonth+'-'+endday;
//

$('#%id%').attr('min', startdate).attr('max', enddate);

**Comment by Olivierkranenburg** [comment]
Wauw, vrij ingewikkeld maar we hebben het gefixed, niet met javascript maar een attribuut met de datum van nu en op het startform twee rules. 
(credits --> Matthijs)

**Comment by EdwinSmink** [comment]
Mooi

**Comment by Olivierkranenburg** [comment]
Bedankt voor de hulp in ieder geval, fijne avond nog
