### ISSUE TITLE
Een rol de mogelijkheid geven om rechten aan te passen (COB-28)

### ISSUE THREAD

**Issue by barthoeksma** [EdwinSmink/Gemboxx#25]
Voor COB-28 moeten we het volgende voor elkaar krijgen: "Als adviseur wil ik toegang tot de persoonsgegevens van een relatie kunnen beperken voor anderen zodat de privacy van mijn relaties gewaarborgd blijft."
Hiervoor zou de adviseur dus de mogelijkheid moeten hebben om de rechten van andere soorten gebruikers in te stellen (in verband met wat die gebruikers wel/niet mogen zien), maar we konden nergens vinden hoe we vanuit een lopende activiteit, rechten aan konden passen.

**Comment by EdwinSmink** [comment]
Ik stel voor om deze te laten schieten. Je zou bijvoorbeeld een andere rol kunnen toekennen. Ik ga er vanuit dat het altijd rol gebaseerd is. Als het beperkt is dan zou je dat met een specifieke toewijzing kunnen doen. Maar dat is wel ingewikkeld, ik weet 'm ook zo een twee drie niet.
