### ISSUE TITLE
Training uitgifte rijbewijs

### ISSUE THREAD

**Issue by ceijssen** [EdwinSmink/Gemboxx#26]
Hoi Edwin,

Lynette en ik begrijpen iets uit de use case niet. Er wordt namelijk regelmatig verwezen(denken we?) naar zaken, zoals "De use case vervolgt op {actualiseren zaak} [1].". Is {behandelen zaak} een status? Of moeten dit activiteiten zijn? 

Ook vragen we ons af of dit een keuzemoment is: 
"Als op {behandelen zaak} [1], dan
10. Behandelaar accordeert aanvraagformulier rijbewijs.
11. Systeem stuurt aanvraagformulier rijbewijs naar CRB (zie BRG-08-01 en MRG-08-01).

12. De use case vervolgt op {actualiseren zaak} [1].
13. Use case wacht tot rijbewijs wordt opgehaald.

Als op {zaak geactualiseerd} [1], dan
14. Behandelaar selecteert aanvraag rijbewijs.
15. Systeem toont aanvraag rijbewijs."

Groetjes

**Comment by EdwinSmink** [comment]
Behandelen en actualiseren zaak zijn activiteiten. Deze activiteiten zijn bedoeld om het zaakgericht werken van de overheid te realiseren. Veel BZM zijn gericht op verzamelen van informatie en als alle gegevens beschikbaar is wordt er in het zaken magazijn een zaak aangemaakt. Omdat wij niet echt een front en backoffice gebruiken is het voor ons een activiteit die de gegevens naar een andere omgeving overbrengt en vervolgens gaat het proces door met de volgende stap.
Dus stap 10 is een stap in de flow, waarbij de voorgaande stap een onderwater update is naar een andere database.
Maak de stap expliciet en vervolg met de volgende stap.

**Comment by LynetteJoosten** [comment]
![uml_afgifte_rijbewijs](https://cloud.githubusercontent.com/assets/11501668/6705729/079cc1c0-cd58-11e4-94f0-d3e65d95fac0.jpg)
Hi Edwin, dit is wat we tot nu toe hebben als activity diagram. Bedoel je dat we dan voor de stap "Accordeert aanvraagformulier rijbewijs" een activiteit moeten toevoegen waarin de zaak behandeld wordt? En wat doet die activiteit dan precies?

**Comment by EdwinSmink** [comment]
Zaak behandelen hoef je niet toe te voegen, zaak aanmaken en zaak actualiseren kan een activity zijn die door het systeem wordt uitgevoerd zodra de functionele taak die daar aan voorafgaat is uitgevoerd.
Zaak behandelen is idd meer een status dingetje, of een overdracht van balie naar backoffice. Het schema ziet er goed uit.
