### ISSUE TITLE
Attribute in case laten aanpassen vanuit andere case

### ISSUE THREAD

**Issue by LynetteJoosten** [EdwinSmink/Gemboxx#27]
Ik ben met COB-17 bezig. Hierin leg ik vast of de verblijfspas ontvangen is. De uitkomst hiervan (Ja/Nee) wil ik graag direct aanpassen in het casetype Pashouders (vanuit waar de pashouder opgevraagd wordt en alle informatie m.b.t. de pashouder staat). Hoe doe ik dit?

**Comment by EdwinSmink** [comment]
Staat deze activiteit niet direct op de case van de pashouder? Ik zou zeggen dat Pashouder (potentieel en daadwerkelijk nadat de pas is uitgedeeld) een aantal activiteiten heeft waarmee we de gegevens bijhouden.

**Comment by LynetteJoosten** [comment]
Ik kom er nog steeds niet uit.. Als ik nu een pashouder selecteer en aangeef of deze een verblijfspas ontvangen heeft, dan maakt 'ie een nieuwe pashouder aan. (Ik snap dat dit komt omdat de activity een nieuwe case "pashouder" aanmaakt elke keer) Hoe zorg ik ervoor dat 'ie alleen het veld "Verblijfspas ontvangen" verandert?

https://dev.grexx.net/TrainingGemboxx27_O/person/case.jsp?case=1832111@traininggemboxx27.nl&stm=1427274302573

**Comment by EdwinSmink** [comment]
Dit komt omdat de activiteit van het type 'Casetype' is. Hierdoor wordt er altijd een case aangemaakt. Als je een activiteit hebt van het type activiteit dan pas je gegevens aan in de case waarop de activiteit staat.

**Comment by LynetteJoosten** [comment]
Het lukt nu om toe te voegen of iemand een verblijfspas heeft of niet. Dit kan nu alleen voor één bepaald persoon, terwijl ik graag uit elke pashouder zou willen kiezen. Hij pakt nu de case van de pashouder waar hij al in zit. Hoe zorg ik ervoor dat ik uit alle pashouders kan kiezen?

**Comment by EdwinSmink** [comment]
Door een Grid te definieren met alle pashouders, deze grid uit te vragen in het attribuut.

**Comment by LynetteJoosten** [comment]
We hebben een grid met alle pashouders, alleen staat in de case "Pashouder" alleen de pashouder die zojuist is aangemaakt en niet alle pashouders die daarvoor ook zijn aangemaakt.

**Comment by EdwinSmink** [comment]
Ah, je wilt een pashouder selecteren en dan aangeven of deze een pas heeft ontvangen.
Dit kun je doen door de widget met pashouders op het platform teplaatsen en een add activity te maken op de grid en een edit activity. In die gevallen krijg je een voeg toe knop en een potloodje. Als de activiteit COB17 is die als edit activiteit hebt staan dan kun je vanuit de grid de pas bijwerken

**Comment by LynetteJoosten** [comment]
Dank! Het toevoegen gaat nu goed, als ik echter op het 'edit' knopje klik, krijg ik dit:
![image](https://cloud.githubusercontent.com/assets/11501668/6823057/e3dd21fc-d2e4-11e4-9f25-3a3e467605c2.png)

**Comment by EdwinSmink** [comment]
Je hebt niet de activiteit gekoppeld waarmee je bij de pashouder kunt aangeven dat de pas ontvangen is. Ik heb dat nu wel gedaan.

**Comment by LynetteJoosten** [comment]
Ik probeer nu hetzelfde te doen met het toevoegen van een afspraak aan een pashouder, alleen heb je natuurlijk maar één edit activity in de widget zitten. Hoe kan ik dit nu het beste aanpakken? (Het gaat om datum afspraak)

https://dev.grexx.net/TrainingGemboxx27_O/person/case.jsp?case=1825291@TrainingGemboxx27.nl&stm=1427285373495&stm=1427285430100

**Comment by EdwinSmink** [comment]
Combineren van beiden in 1 form. Anders moet je echt naar de case toe om daar de actie uit te voeren. In principe heb je in elke casetype een proces flow zitten. Een afspraak maak je met de pashouder. Ik verwacht dat we dan eerste de pashouder openen en daarbinnen de taak hebben om een afspraak te maken. Je kunt ook een casetype afspraak maken waarin je de pashouder ophaalt

**Comment by LynetteJoosten** [comment]
Ik heb een nieuw casetype "Pashouder afspraak", waarin ik de pashouder opvraag en de afspraak vastleg. Ik kan nu in de widget als ik op edit klik wel kiezen uit een lijst met data, maar ik zou graag willen dat alleen de datum van de pashouder daar komt te staan. In het casetype "pashouder" staat een widget met alle afspraken van pashouders. Hoe krijg ik dit voor elkaar?

**Comment by EdwinSmink** [comment]
Ik begrijp je niet. Kun je de widget aanwijzen, het form heeft nu drie attributen als je een edit doet op pashouder. De datum van de afspraak zou ik een date veld maken tenzij je op 1 dag alle afspraken al wilt tonen zodat daar uitgekozen kan worden of juist niet meer gekozen kan worden.

**Comment by LynetteJoosten** [comment]
https://dev.grexx.net/TrainingGemboxx27_O/person/case.jsp?case=1825291@TrainingGemboxx27.nl&stm=1427296445307
Het gaat om de widget bovenaan, genaamd pashouders. En dan om de kolom met daarin de datum van de afspraak.

Als er een afspraak wordt gemaakt voor een pashouder, dan wordt dit gekoppeld aan de pashouder. Deze datum zou ik graag als enige willen tonen in het edit form. Deze afspraken zijn te vinden in de widget "Afspraken" in het casetype "Pashouder". Deze worden aangemaakt in het casetype "Pashouder afspraak".

**Comment by EdwinSmink** [comment]
Als je de query er vanaf haalt dan wordt deze automatisch overgenomen uit de case. Dan ben je klaar, denk ik
