### ISSUE TITLE
Vraag: Datum check

### ISSUE THREAD

**Issue by CoenPijpers** [EdwinSmink/Gemboxx#30]
Ik wil bij een activiteit een map-out creëren als de datum < nu DAN wordt de case state 1000.
Dus als een werknemer stopt met werken: einddatum.
Dan einddatum < datum van vandaag. Dan MAP OUT metadata state = 1000.

Hoe zet je de conditie op die MAP OUT?

**Comment by mteerlink** [comment]
Je kan een date attribuut aanmaken met als default waarde now(). Dan een map-out maken die de state op 1000 zet en op die map-out een conditie einddatum < date now attribuut.

Ik weet alleen niet of now() automatisch update naar de dag van vandaag. Als dat niet zo is moet je een map-in op de activiteit zetten die het datum van nu attribuut update door het de waarde now() te geven.

**Comment by CoenPijpers** [comment]
Heb een attribuut gemaakt: Datum_Vandaag
Heeft een default waarde: now()
Heb bij de MAP OUT die de state op 1000 zet, gezegd die conditie einddatum < Datum_vandaag

Doet ie niet...

**Comment by CoenPijpers** [comment]
Hij doet het!
Inderdaad de map-in zorgt voor de waarde. Niet de default waarde bij het attribuut Datum Vandaag.

Thanks!
