### ISSUE TITLE
Rollen & rechten

### ISSUE THREAD

**Issue by Olivierkranenburg** [EdwinSmink/Gemboxx#36]
Ik ben al even bezig met de rollen en rechten toevoegen maar kom er niet uit.
Ik heb op platform home onder administration --> users alle users toegevoegd:
- Aspirant_Medewerker
- Junior_Medewerker
- Senior_Medewerker
- Voormalig_Medewerker
- Delivery_Manager
- Sales_Manager
Ook heb ik op platform home onder roles de rollen toegevoegd.
Daarna heb ik op platform home de rollen gekoppeld aan users onder Case Direct Roles.
Nu kan ik de widgets rechten geven op het platform.
Nu wil ik de activiteiten rechten geven in de casetypes maar weet niet precies hoe.
Ik zie veel mogelijkheden maar voordat ik alles ga proberen kan iemand mij op weg helpen?

**Comment by RowanvPelt** [comment]
Kun je niet gewoon binnen je case naar --> case activities --> de activiteit waar je rechten aan wilt geven --> meest rechtse kolom (rights) --> voeg toe --> en dan de rol selecteren?

Of is dit niet wat je bedoeld?

**Comment by Olivierkranenburg** [comment]
Nee dat werkt dus niet, en weet niet hoe ik dat fix. De rechten zijn aangemaakt op het platform maar moeten nu beschikbaar zijn binnen de casetypes. Iets met indirecte rollen denk ik maar weet niet of dat vanaf het platform moet of casetype niveau oid, heb het idee dat ik nog iets mis

**Comment by jasperschenkhuizen** [comment]
indirecte rollen toevoegen moet je vanaf je case doen volgens mij, 
case indirect roles -> toevoegen -> role: invullen, en -> attribute: platform home invullen

**Comment by Olivierkranenburg** [comment]
Thanks Jasper dat werkt :)
