### ISSUE TITLE
IMB: case in widget alleen laten zien als attribuut bepaalde waarde heeft.

### ISSUE THREAD

**Issue by LynetteJoosten** [EdwinSmink/Gemboxx#37]
Op platform home staat een widget "Trainingsoverzicht". Ik wil alleen de medewerkers laten zien die als Status_Medewerker "Aspirant" hebben (dit zijn de medewerkers die de training nog moeten volgen).
Hoe doe ik dit? Ik heb het al geprobeerd met de conditions, maar dat lukte niet helemaal..

**Comment by mteerlink** [comment]
De conditie = 'Aspirant' (met aanhalingstekens om aspirant) zou moeten werken.

**Comment by LynetteJoosten** [comment]
Thanks!
