### ISSUE TITLE
Attribuut al dan niet hide'en (verbergen)

### ISSUE THREAD

**Issue by Gaiusnoordhoek** [EdwinSmink/Gemboxx#45]
Hoi,

Bij een zelfgemaakte persoonsgegevens case heb ik een attribuut met een picklist van vrouwelijke adellijke titels en eentje van mannelijke adellijke titels. Ik zou willen dat de vrouwelijke picklist pas tevoorschijn komt als bij het attribuut (ook een picklist) "voorvoegsel" Mevrouw wordt geklikt, en de mannelijke pas bij Dhr.

Ik wil dus dat bepaalde attributen pas verschijnen aan de hand van de uitslag van een ander attribuut. 

Bij de vorige training was dat even laten zien, maar het is me alweer helemaal ontschoten, en zit er nu al een tijdje mee. Kan iemand me helpen?

Mvg,
Gaius

**Comment by EdwinSmink** [comment]
Als je het formulier opent in developer mode (door de activiteit te starten) zie je links bovenaan een aantal letters staan. De L staat voor Logic (form logic). Hiermee kun je het gedrag van de velden op het scherm beïnvloeden.
In de presentatie van de trainingsdag 2 staat hoe. Ik heb die gemailed.

**Comment by EdwinSmink** [comment]
Als dit het juiste antwoord is dan graag de issue sluiten. Als er een nieuwe vraag komt dan een nieuw issue openen

**Comment by Gaiusnoordhoek** [comment]
Dank Edwin
